version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest 
     generate_cohort
     --study-definition study_definition
     --index-date-range "2019-03-01 to 2020-01-01 by month"
     --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_measures:
    run: >
     cohortextractor:latest 
     generate_measures 
     --study-definition study_definition
     --output-dir=output/measures
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        measure_csv: output/measure_*.csv
